ARG IMAGE
FROM ${IMAGE}

ARG UID=1000
ARG USER=builder
ARG ARCH

RUN useradd -m -u ${UID} -s /bin/bash ${USER}

# Non-interactive configuration of tzdata
ENV DEBIAN_FRONTEND noninteractive
ENV DEBCONF_NONINTERACTIVE_SEEN true
RUN { echo 'tzdata tzdata/Areas select Etc'; echo 'tzdata tzdata/Zones/Etc select UTC'; } | debconf-set-selections

RUN apt-get update
RUN apt-get install -y cmake gdb python3 python3-pip openssh-server mc rsync libgpiod-dev
RUN pip3 install conan

USER ${USER}
RUN mkdir -p /home/${USER}/.ssh
RUN mkdir -p /home/${USER}/rpi-robot/cmake-build-debug-${ARCH}
RUN mkdir -p /home/${USER}/.conan2

COPY docker-configs/authorized_keys /home/${USER}/.ssh/authorized_keys
RUN conan profile detect --force
COPY docker-configs/conan.${ARCH}.profile /home/${USER}/.conan2/profiles/default
COPY conanfile.txt /home/${USER}/rpi-robot/conanfile.txt
WORKDIR /home/${USER}/rpi-robot
RUN conan install . --output-folder=cmake-build-debug-${ARCH} --build=missing

USER root
RUN service ssh start
EXPOSE 22
CMD ["/usr/sbin/sshd","-D"]