FROM arm64v8/debian:bullseye

ARG UID=1000
RUN useradd -m -u ${UID} -s /bin/bash builder

# Non-interactive configuration of tzdata
#ENV DEBIAN_FRONTEND noninteractive
#ENV DEBCONF_NONINTERACTIVE_SEEN true
RUN { echo 'tzdata tzdata/Areas select Etc'; echo 'tzdata tzdata/Zones/Etc select UTC'; } | debconf-set-selections

RUN apt-get update
RUN apt-get install -y cmake gdb python3 python3-pip openssh-server mc rsync
RUN pip3 install conan==1.59

USER builder
RUN mkdir -p /home/builder/.ssh
RUN mkdir -p /home/builder/rpi-robot/cmake-build-debug-dockerhost
RUN mkdir -p  /home/builder/.conan/profiles

COPY docker-configs/authorized_keys /home/builder/.ssh/authorized_keys
COPY conanfile.txt /home/builder/rpi-robot/conanfile.txt
COPY docker-configs/conan.profile /home/builder/.conan/profiles/default
WORKDIR /home/builder/rpi-robot

#RUN conan profile detect --force
WORKDIR /home/builder/rpi-robot/cmake-build-debug-dockerhost
RUN conan install .. --build=missing

USER root
RUN service ssh start
EXPOSE 22
CMD ["/usr/sbin/sshd","-D"]