ARG IMAGE
FROM ${IMAGE}

ARG UID=1000
ARG USER=debugger

RUN useradd -m -u ${UID} -s /bin/bash ${USER}

# Non-interactive configuration of tzdata
#ENV DEBIAN_FRONTEND noninteractive
#ENV DEBCONF_NONINTERACTIVE_SEEN true
RUN { echo 'tzdata tzdata/Areas select Etc'; echo 'tzdata tzdata/Zones/Etc select UTC'; } | debconf-set-selections

RUN apt-get update
RUN apt-get install -y cmake gdb openssh-server mc gdbserver


USER ${USER}
RUN mkdir -p /home/${USER}/.ssh

COPY docker-configs/id_rsa_builder.pub /home/${USER}/.ssh/authorized_keys

USER root
RUN service ssh start
EXPOSE 22
EXPOSE 1234
CMD ["/usr/sbin/sshd","-D"]