ARG IMAGE
FROM ${IMAGE}

ARG UID=1000
ARG USER=builder
RUN useradd -m -u ${UID} -s /bin/bash ${USER}

# Non-interactive configuration of tzdata
#ENV DEBIAN_FRONTEND noninteractive
#ENV DEBCONF_NONINTERACTIVE_SEEN true
RUN { echo 'tzdata tzdata/Areas select Etc'; echo 'tzdata tzdata/Zones/Etc select UTC'; } | debconf-set-selections

RUN apt-get update
RUN apt-get install -y cmake gdb python3 python3-pip openssh-server mc rsync libgpiod-dev wget
RUN pip3 install conan==1.59

USER ${USER}
RUN mkdir -p /home/${USER}/.ssh
RUN mkdir -p /home/${USER}/rpi-robot/cmake-build-debug-dockerhost
RUN mkdir -p  /home/${USER}/.conan/profiles

COPY docker-configs/authorized_keys /home/${USER}/.ssh/authorized_keys
COPY conanfile.txt /home/${USER}/rpi-robot/conanfile.txt
COPY docker-configs/conan.profile /home/${USER}/.conan/profiles/default
WORKDIR /home/${USER}/rpi-robot

#RUN conan profile detect --force
WORKDIR /home/${USER}/rpi-robot/cmake-build-debug-dockerhost
RUN conan install .. --build=missing

USER root
RUN service ssh start
EXPOSE 22
CMD ["/usr/sbin/sshd","-D"]