version: '3'
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./docker-data/prometheus/config:/etc/prometheus/
      - ./docker-data/prometheus/data:/prometheus
    command:
      - '-config.file=/etc/prometheus/prometheus.yml'
      - '-storage.local.path=/prometheus'
      - '-alertmanager.url=http://alertmanager:9093'
    expose:
      - 9090
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    links:
      - prometheus:prometheus
    volumes:
      - ./docker-data/grafana:/var/lib/grafana
    ports:
      - 3000:3000

  rabbitmq:
    build:
      context: ./
      dockerfile: DockerFile_rabbitmq
    container_name: rabbitmq
    ports:
      - "5671:5671"
      - "5672:5672"
      - "15672:15672"
      - "1883:1883"
      - "8884:8883"

  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 1234
    volumes:
      - ./docker-data/postgresql:/var/lib/postgresql/data

  # builder for Raspberry PI Zero 2, 3, 4
  builder_arm64v8:
    security_opt:
      - seccomp:unconfined/home/builder/rpi-robot/cmake-build-debug-armv8
    build:
      context: .
      dockerfile: Dockerfile_builder
      args:
        UID: 1000
        USER: builder
        ARCH: armv8
        IMAGE: arm64v8/debian:bullseye
    container_name: builder_arm64v8
    ports:
      - "2022:22"
    volumes:
      - ./docker-debug-armv8/bin:/home/builder/rpi-robot/cmake-build-debug-armv8/bin
      - ./docker-debug-armv8/etc:/home/builder/rpi-robot/cmake-build-debug-armv8/etc

  # builder for Banana PI Berry
  builder_arm32v7:
    security_opt:
      - seccomp:unconfined
    build:
      context: .
      dockerfile: Dockerfile_builder
      args:
        UID: 1000
        USER: builder
        ARCH: armv7
        IMAGE: arm32v7/debian:bullseye
        CONAN: conan-arm32v7.profile
    container_name: builder_arm32v7
    ports:
      - 2023:22
    volumes:
      - ./docker-debug-armv7/bin:/home/builder/rpi-robot/cmake-build-debug-armv7/bin
      - ./docker-debug-armv7/etc:/home/builder/rpi-robot/cmake-build-debug-armv7/etc

  simulator_arm64v8:
    security_opt:
      - seccomp:unconfined
    build:
      context: .
      dockerfile: Dockerfile_simulator
      args:
        UID: 1000
        USER: debugger
        IMAGE: arm64v8/debian:bullseye
    container_name: simulator_arm64v8
    ports:
      - "3022:22"
      - "1234:1234"
    volumes:
      - ./docker-debug-armv8/etc:/home/debugger/etc

  simulator_arm32v7:
    security_opt:
      - seccomp:unconfined
    build:
      context: .
      dockerfile: Dockerfile_simulator
      args:
        UID: 1000
        USER: debugger
        IMAGE: arm32v7/debian:bullseye
    container_name: simulator_arm32v7
    ports:
      - "3023:22"
      - "1235:1234"
    volumes:
      - ./docker-debug-armv8/etc:/home/debugger/etc