global:
  resolve_timeout: 5m
route:
  receiver: "null"
  group_by:
    - namespace
  routes:
    - receiver: "null"
      matchers:
        - alertname =~ "InfoInhibitor|Watchdog"
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
inhibit_rules:
  - target_matchers:
      - severity =~ warning|info
    source_matchers:
      - severity = critical
    equal:
      - namespace
      - alertname
  - target_matchers:
      - severity = info
    source_matchers:
      - severity = warning
    equal:
      - namespace
      - alertname
  - target_matchers:
      - severity = info
    source_matchers:
      - alertname = InfoInhibitor
    equal:
      - namespace
receivers:
  - name: "null"
templates:
  - /etc/alertmanager/config/*.tmpl