version: '3'
services:

  grafana:
    build:
      context: ./
      dockerfile: DockerFile_Grafana
    container_name: grafana
    ports:
      - 3000:3000

  rabbitmq:
    build:
      context: ./
      dockerfile: DockerFile_RabbitMQ
    container_name: rabbitmq
    ports:
      - 5671:5671
      - 5672:5672
      - 15672:15672
      - 1883:1883
      - 8883:8883
