FROM grafana/grafana-plugin-ci:1.6.0-alpine as build

ADD grafana-plugins /var/lib/grafana/plugins
WORKDIR /var/lib/grafana/plugins/mqtt-datasource

RUN yarn install
RUN yarn build

FROM grafana/grafana:9.2.6 AS grafana
ENV GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS="grafana-mqtt-datasource"
COPY --from=build /var/lib/grafana/plugins/mqtt-datasource /var/lib/grafana/plugins/mqtt-datasource